<?php 
class idiomas{
	function español(){
$arrays=array(
	"Usuario"=>"Usuario" ,
	"Datosmonitor"=>"Datos del monitor",
	"Datosdeportista"=>"Datos del Deportista",
	"Password"=>"Contraseña",
	"FechaNac"=>"Fecha  de Nacimiento",
	"Configuracion"=>"Configuracion",
	"Nombre"=>"Nombre",
	"Apellidos"=>"Apellidos",
	"Apellido1"=>"Apellido1",
	"Apellido2"=>"Apellido2",
	"Telefono"=>"Telefono",
	"email"=>"Email del Usuario",
	"Gallego"=>"Gallego",
	"Español"=>"Español",
	"Ingles"=>"Ingles",
	"DNI"=>"DNI",
	"Perfil"=>"Perfil",
	"TIPO"=>"Tipo",
	"notificacion"=>"Crear Notificacion",
	"Notificacion1"=>"Notificacion",
	"Menu"=>"Menu Principal",
	"AltaSesion"=>"Alta Sesion",
	"GestionDeportista"=>"Gestion de Deportistas",
	"GestionMonitores"=>"Gestion de Monitores",
	"GestionActividades"=>"Gestion de Actividades",
	"notificacioninsertada"=>"Enviada la notificacion",
	"GestionNotificaciones"=>"Gestion de Notificaciones",
	"GestionSesiones"=>"Gestion de Sesiones",
	"GestionReservas"=>"Gestion de Reservas",
	"GestionTablas"=>"Gestion de Tablas",
	"GestionEjercicios"=>"Gestion de Ejercicios",
	"Reset"=>"Reset",
	"salir"=>"salir",
	"Altarealizada"=>"Insercion Realizada",
	"Altaerronea"=>"Rellene los campos necesarios",
	"DatosActividad"=>"Datos de la Actividad",
	"Duracion"=>"Duracion",
	"Hora"=>"Hora",
	"Lugar" =>"Lugar",
	"Plazas"=>"Plazas",
	"Dificultad"=>"Dificultad",
	"mensaje"=>"Mensaje",
	"Fecha"=>"Fecha",
	"Id_actividad"=>"Id Actividad",
	"Descripcion"=>"Descripcion",
	"AltaActividad"=>"Alta Actividad",
	"ModificarActividad"=>"Modificar Actividad",
	"Fecha"=>"Fecha",
	"Monitor"=>"Entrenador",
	"dnierroneo"=>"Por favor,Introduzca otro dni",
	"Deportista"=>"Deportista",
	"Comentario"=>"Comentario",
	"Ejercicio"=>"Ejercicio",
	"Sesion"=>"Sesion",
	"mostrartodos"=>"Mostrar Todos",
	"de"=>"DE",
	"to"=>"PARA",
	"confirmareliminado"=>"¿Esta seguro de que desea eliminar esta notificacion?",
	"foto"=>"FOTO",
	"borrartodo"=>"Borrar Todo",
	"confirmareliminados"=>"¿Esta seguro de que desea eliminar estas notificaciones?",
	"Tabla"=>"Tabla"
	);

return $arrays;
}
function gallego(){

$arrays=array(
	"Usuario"=>"Usuario" ,
	"Datosmonitor"=>"Datos do monitor",
	"Datosdeportista"=>"Datos do Deportista",
	"Password"=>"Contrasinal",
	"FechaNac"=>"Data de Nacimiento",
	"AltaSesion"=>"Alta Sesion",
	"Nombre"=>"Nome",
	"Apellidos"=>"Apelidos",
	"Apellido1"=>"Apelido1",
	"Apellido2"=>"Apellido2",
	"Configuracion"=>"Configuracion",
	"Telefono"=>"Telefono",
	"email"=>"Email do Usuario",
	"DNI"=>"DNI",
	"Gallego"=>"Galego",
	"Español"=>"Español",
	"Ingles"=>"Ingles",
	"Perfil"=>"Perfil",
	"TIPO"=>"Tipo",
	"Menu"=>"Menu Principal",
	"GestionDeportista"=>"Xestion de Deportistas",
	"GestionMonitores"=>"Xestion de Monitores",
	"GestionActividades"=>"Xestion de Actividades",
	"GestionNotificaciones"=>"Xestion de Notificacions",
	"GestionSesiones"=>"Xestion de Sesiones",
	"GestionReservas"=>"Xestion de Reservas",
	"GestionTablas"=>"Xestion de Tablas",
	"GestionEjercicios"=>"Xestion de Ejercicios",
	"Reset"=>"Rest",
	"salir"=>"sair",
	"Altarealizada"=>"Insercion Realizada",
	"Altaerronea"=>"Enche os campos necesarios",
	"DatosActividad"=>"Datos da Actividade",
	"Duracion"=>"Duracion",
	"Hora"=>"Hora",
	"Lugar"=>"Lugar",
	"Plazas"=>"Prazas",
	"Dificultad"=>"Dificultade",
	"Fecha"=>"Data",
	"notificacioninsertada"=>"Enviada a notificacion",
	"Id_actividad"=>"Id Actividade",
	"Descripcion"=>"Descripcion",
	"AltaActividad"=>"Alta Actividade",
	"ModificarActividad"=>"Modificar Actividade",
	"Fecha"=>"Data",
	"Monitor"=>"Entrenador",
	"Deportista"=>"Deportista",
	"Comentario"=>"Comentario",
	"Ejercicio"=>"Exercicio",
	"Sesion"=>"Sesion",
	"mostrartodos"=>"Mostrar Todos",
	"de"=>"DE",
	"to"=>"PARA",
	"confirmareliminado"=>"¿Esta seguro de que desexa eliminar esta notificacion?",
	"foto"=>"IMAXE",
	"notificacion"=>"Crear Notificacion",
	"dnierroneo"=>"Por favor,Introduzca outro dni",
	"Notificacion1"=>"Notificacion",
	"mensaje"=>"Mensaxe",
	"borrartodo"=>"Borrar Todo",
	"confirmareliminados"=>"¿Esta seguro de que desexa eliminar estas notificacions?",
	"Tabla"=>"Tabla"
	);

return $arrays;

}

function ingles(){

$arrays=array(
	"Usuario"=>"User",
	"Password"=>"Password",
	"Datosmonitor"=>"Coach Data",
	"AltaSesion"=>"Insert Session",
	"Datosdeportista"=>"Athlete data",
	"FechaNac"=>"Birthdate",
	"Configuracion"=>"Configuration",
	"Nombre"=>"Name",
	"Apellidos"=>"LastName",
	"Apellido1"=>"LastName1",
	"Apellido2"=>"LastName2",
	"Telefono"=>"Phone",
	"Perfil"=>"Profile",
	"email"=>"Email",
	"DNI"=>"DNI",
	"TIPO"=>"Tipe",
	"Gallego"=>"Galician",
	"notificacion"=>"Make Notifications",
	"Notificacion1"=>"Notifications",
	"Español"=>"Spanish",
	"Ingles"=>"English",
	"Menu"=>"Main menu",
	"GestionDeportista"=>"Athlete Management",
	"GestionMonitores"=>"Monitors Management ",
	"GestionActividades"=>"Activities Management",
	"GestionNotificaciones"=>"Reports Management ",
	"GestionSesiones"=>"Session Management",
	"GestionReservas"=>"Reservs Management ",
	"GestionTablas"=>"Tables Management",
	"GestionEjercicios"=>"Excercises Managemente",
	"Reset"=>"Rest",
	"notificacioninsertada"=>"Notification Sent",
	"salir"=>"Logout",
	"Altarealizada"=>"Insercion Realizada",
	"DatosActividad"=>"Datos de la Actividad",
	"Duracion"=>"Duracion",
	"Hora"=>"Hora",
	"Lugar" =>"Lugar",
	"Plazas"=>"Plazas",
	"Dificultad"=>"Dificultad",
	"Fecha"=>"Fecha",
	"Id_actividad"=>"Id Actividad",
	"Descripcion"=>"Descripcion",
	"AltaActividad"=>"Alta Actividad",
	"ModificarActividad"=>"Modificar Actividad",
	"Altaerronea"=>"Rellene los campos necesarios",
	"DatosActividad"=>"Activities data",
	"Duracion" => "Lenght",
	"Hora" => "Time",
	"Lugar" =>"Place",
	"Plazas" => "Slots",
	"Dificultad" => "Difficulty",
	"Fecha" => "Date",
	"Id_actividad"=> "Id Activity",
	"Descripcion" => "Description",
	"AltaActividad"=>"Create Activity",
 	"ModificarActividad"=>"Edit Activity",
 	"mensaje"=>"Message",
 	"Fecha"=>"Date",
 	"Monitor"=>"Trainer",
 	"Deportista"=>"Athlete",
 	"Comentario"=>"Comment",
 	"Ejercicio"=>"Exercice",
 	"Sesion"=>"Session",
 	"mostrartodos"=>"Show All",
 	"dnierroneo"=>"Please,Insert another identification number card",
 	"de"=>"FROM",
	"to"=>"TO",
	"confirmareliminado"=>"Are you sure that you want to delete this notification?",
	"foto"=>"Picture",
	"borrartodo"=>"Delete All",
	"confirmareliminados"=>"Are you sure that you want to delete this notifications?",
	"Tabla"=>"Tabla"
 	);

return $arrays;

}

}

?>